INPUT_PATH: "/home/swyang/바탕화면/codehub/project/Conrad/landmark/data/input/"
MODEL_PATH: "/home/swyang/바탕화면/codehub/project/Conrad/landmark/data/model/"

GPUs: "0"
   
SPACING: !!python/tuple [1., 1., 1.]

GAMMA: .9
LEARNING_RATE: 1.e-4
MULTIPLE_SCALE: true

KERNEL_SHAPE: !!python/tuple [25, 25, 25]

NUM_AGENT: 2
NUM_ACTION: 6
NUM_BATCH: 6
NUM_FRAME: 4
   
MAX_EPISODE: 500
MAX_STEP_PER_EPISODE: 1000 

OSCILLATIONS: 12
